import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:readrun/Splash_screen.dart';
import 'package:readrun/constants.dart';
import 'package:shared_preferences/shared_preferences.dart';


class OnboardingScreen extends StatefulWidget {
  @override
  _OnboardingScreenState createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends State<OnboardingScreen> {

  final int _numPages = 3;
  final PageController _pageController = PageController(initialPage: 0);
  int _currentPage = 0;

  List<Widget> _buildPageIndicator() {
    List<Widget> list = [];
    for (int i = 0; i < _numPages; i++) {
      list.add(i == _currentPage ? _indicator(true) : _indicator(false));
    }
    return list;
  }
  _setOnBoardStatus()async{
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.setBool("showShowcase", false);
  }

  Widget _indicator(bool isActive) {
    return AnimatedContainer(
      duration: Duration(milliseconds: 150),
      margin: EdgeInsets.symmetric(horizontal: 8.0),
      height: 8.0,
      width: isActive ? 24.0 : 16.0,
      decoration: BoxDecoration(
        color: kPrimaryColor,
        borderRadius: BorderRadius.all(Radius.circular(12)),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final width = MediaQuery.of(context).size.width;
    final height = MediaQuery.of(context).size.height;

    return Scaffold(
      backgroundColor: Colors.white,
      body: AnnotatedRegion<SystemUiOverlayStyle>(
        value: SystemUiOverlayStyle.light,
        child: Container(
          child: Padding(
            padding: EdgeInsets.symmetric(vertical: 40.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: <Widget>[
                Container(
                  alignment: Alignment.centerRight,
                  child: FlatButton(
                    onPressed: () {
                      _setOnBoardStatus();
                        Navigator.pushAndRemoveUntil(context, MaterialPageRoute(builder: (BuildContext context) =>
                        SplashScreen()), (Route<dynamic> route) => route is SplashScreen);
                        },
                    child: Text(
                      'Skip',
                      style: Theme.of(context).textTheme.headline2,
                    ),
                  ),
                ),
                Container(
                  height: height*0.7,
                  child: PageView(
                    physics: ClampingScrollPhysics(),
                    controller: _pageController,
                    onPageChanged: (int page) {
                      setState(() {
                        _currentPage = page;
                      });
                    },
                    children: <Widget>[
                      Padding(
                        padding: EdgeInsets.all(40.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: <Widget>[
                            Center(
                              child: Image(
                                image: AssetImage(
                                  'assets/images/undraw_Artificial_intelligence_oyxx.png',
                                ),
                                height:height*0.4,
                                width: height*0.4,
                              ),
                            ),
                            SizedBox(height: 30.0),
                            Text(
                              'AI Powered News',
                              style: Theme.of(context).textTheme.headline2,
                            ),
                            SizedBox(height: 15.0),
                            Text(
                              'Get the short summary of latest news generated by our A.I. model',
                              style: Theme.of(context).textTheme.bodyText1,
                            ),
                          ],
                        ),
                      ),
                      Padding(
                        padding: EdgeInsets.all(40.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: <Widget>[
                            Center(
                              child: Image(
                                image: AssetImage(
                                  'assets/images/undraw_Share_re_9kfx.png',
                                ),
                                height:height*0.4,
                                width: height*0.4,
                              ),
                            ),
                            SizedBox(height: 30.0),
                            Text(
                              'Easy Share',
                              style: Theme.of(context).textTheme.headline2,
                            ),
                            SizedBox(height: 15.0),
                            Text(
                              'Easily share the latest news with friends and family with one touch',
                              style: Theme.of(context).textTheme.bodyText1,
                            ),
                          ],
                        ),
                      ),
                      Padding(
                        padding: EdgeInsets.all(40.0),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: <Widget>[
                            Center(
                              child: Image(
                                image: AssetImage(
                                  'assets/images/undraw_on_the_office_fbfs.png',
                                ),
                                height:height*0.4,
                                width: height*0.4,
                              ),
                            ),
                            SizedBox(height: 30.0),
                            Text(
                              'You are the BOSS here',
                              style: Theme.of(context).textTheme.headline2,
                            ),
                            SizedBox(height: 15.0),
                            Text(
                              'Decide yourself how many notifications you want on daily basis',
                              style: Theme.of(context).textTheme.bodyText1,
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: _buildPageIndicator(),
                ),
                Spacer(),
                _currentPage != _numPages - 1
                    ? Expanded(
                  child: Align(
                    alignment: FractionalOffset.bottomRight,
                    child: FlatButton(
                      onPressed: () {
                        _pageController.nextPage(
                          duration: Duration(milliseconds: 500),
                          curve: Curves.ease,
                        );
                      },
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        mainAxisSize: MainAxisSize.min,
                        children: <Widget>[
                          Text(
                            'Next',
                            style: Theme.of(context).textTheme.headline2,
                          ),
                          SizedBox(width: 10.0),
                          Icon(
                            Icons.arrow_forward,
                            color: kPrimaryColor,
                            size: 30.0,
                          ),
                        ],
                      ),
                    ),
                  ),
                )
                    : Text(''),
              ],
            ),
          ),
        ),
      ),
      bottomSheet: _currentPage == _numPages - 1
          ? Container(
        height: height*0.1,
        width: double.infinity,
        color: kSecondaryColor,
        child: GestureDetector(
          onTap: (){
      _setOnBoardStatus();
      Navigator.pushAndRemoveUntil(context, MaterialPageRoute(builder: (BuildContext context) =>
      SplashScreen()), (Route<dynamic> route) => route is SplashScreen);
      },
          child: Center(
            child: Padding(
              padding: EdgeInsets.only(bottom: 20.0),
              child: Align(
                alignment: Alignment.center,
                child: Text(
                  'Get started',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20.0,
                    fontFamily: "CharterITC",
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ),
          ),
        ),
      )
          : SizedBox(height: 0,),
    );
  }
}