language: python

python:
    - "3.8"
install:
    - pipenv install
services:
    - docker
before_script:
    - cd Backend/
    - pip install docker-compose
script:
    - docker-compose run web sh -c "python3 manage.py test"