language: python

python:
    - "3.8"
install:
    - pipenv install
services:
    - docker
before_script:
    - cd Backend/
    - pip install docker-compose
    - docker build -t  pushkarasharma11/scoopfeeds:latest .
script:
    - docker-compose run web sh -c "python3 Scoopfeeds/manage.py test"
    - docker tag scoopfeeds:latest pushkarasharma11/scoopfeeds:latest
    - docker push pushkarasharma11/scoopfeeds:latest
before_deploy:
  - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}