# Generated by Django 4.0.1 on 2022-01-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('heading', models.CharField(default='', max_length=1000)),
                ('summary', models.TextField(default='')),
                ('image_url', models.TextField(default='')),
                ('news_type', models.CharField(default='', max_length=225)),
            ],
        ),
    ]
